"""
thermal_model.py
================
Physics-based thermal model of a single-zone data centre.

WHY THIS FILE EXISTS:
    The RL environment needs to simulate how temperature changes when
    we take cooling actions. This file contains that physics logic,
    kept separate from the Gym environment for clean code structure.

PHYSICS USED:
    Newton's Law of Cooling + Energy Balance:
    dT/dt = (Q_in - Q_out) / (thermal_mass)

    Where:
        Q_in  = heat generated by servers (function of CPU load)
        Q_out = heat removed by CRAC unit (function of setpoint)
"""

import numpy as np


class ThermalModel:
    """
    Models the thermal dynamics of a single server room zone.

    Parameters
    ----------
    thermal_mass : float
        How much thermal inertia the room has (higher = slower temp change).
        Think of it like how long it takes a room to heat up or cool down.
        Units: kJ/°C
    """

    def __init__(self, thermal_mass: float = 500.0):
        self.thermal_mass = thermal_mass  # kJ/°C

        # ASHRAE Thermal Guidelines for Data Centres
        # These are real industry standards based on real data
        self.TEMP_MIN = 18.0   # °C — minimum safe server inlet temp
        self.TEMP_MAX = 27.0   # °C — maximum safe server inlet temp
        self.TEMP_CRITICAL = 35.0  # °C — hardware throttling begins

    def step(
            self,
            current_temp: float,
            server_load_kw: float,
            crac_setpoint: float,
            outside_temp: float,
            dt_seconds: float = 60.0
    ) -> dict:
        """
        Advance the thermal simulation by one timestep.

        Parameters
        ----------
        current_temp    : current server room temperature (°C)
        server_load_kw  : current IT load generating heat (kW)
        crac_setpoint   : temperature CRAC is trying to supply (°C)
        outside_temp    : outdoor temperature (affects cooling efficiency)
        dt_seconds      : timestep duration in seconds (default: 60s = 1 min)

        Returns
        -------
        dict with:
            new_temp      : updated room temperature (°C)
            crac_power_kw : energy consumed by CRAC (kW)
            pue           : Power Usage Effectiveness
            cop           : Coefficient of Performance of CRAC
        """

        # --- HEAT IN: Servers generate heat proportional to load ---
        # Servers convert almost all electrical power to heat
        # Q_servers is in kW
        q_servers_kw = server_load_kw  # 1 kW electrical = ~1 kW heat

        # --- HEAT OUT: CRAC cooling power ---
        # How hard the CRAC works depends on the temperature difference
        # between the room and the target setpoint
        temp_delta = current_temp - crac_setpoint  # how much cooling needed

        # COP (Coefficient of Performance) — key efficiency metric
        # COP = cooling output / electrical input
        # Higher outside temp = lower COP (harder to reject heat outside)
        # This is real physics — mention it in interviews!
        cop = self._calculate_cop(crac_setpoint, outside_temp)

        # Cooling capacity of CRAC (how much heat it can remove)
        # Proportional to temp difference, limited by max capacity
        max_cooling_kw = 150.0  # typical CRAC unit capacity
        q_cooling_kw = np.clip(temp_delta * 8.0, 0, max_cooling_kw)

        # Electrical power consumed by CRAC to deliver that cooling
        crac_power_kw = q_cooling_kw / cop if cop > 0 else q_cooling_kw

        # --- TEMPERATURE CHANGE ---
        # Energy balance: net heat = heat in - heat out
        net_heat_kw = q_servers_kw - q_cooling_kw

        # Convert power to temperature change:
        # dT = (net_heat_kW * dt_seconds) / thermal_mass
        # thermal_mass in kJ/°C, power in kW = kJ/s
        delta_temp = (net_heat_kw * dt_seconds) / self.thermal_mass

        new_temp = current_temp + delta_temp

        # Physical bounds — room can't go below outside temp or above 60°C
        new_temp = np.clip(new_temp, outside_temp - 5, 60.0)

        # --- PUE Calculation ---
        # PUE = Total Facility Power / IT Equipment Power
        # Best possible = 1.0 (all power goes to servers, none wasted on cooling)
        # Google's data centres average ~1.10, industry average ~1.55
        total_power_kw = server_load_kw + crac_power_kw
        pue = total_power_kw / server_load_kw if server_load_kw > 0 else 2.0

        return {
            "new_temp": float(new_temp),
            "crac_power_kw": float(crac_power_kw),
            "pue": float(pue),
            "cop": float(cop),
            "q_cooling_kw": float(q_cooling_kw),
            "net_heat_kw": float(net_heat_kw),
        }

    def _calculate_cop(self, crac_setpoint: float, outside_temp: float) -> float:
        """
        Calculate Coefficient of Performance using Carnot efficiency.

        Real COP depends on the temperature lift required:
        - Small lift (cool outside) = easy = high COP
        - Large lift (hot outside)  = hard = low COP

        This is the Carnot COP formula — theoretical maximum efficiency.
        Real systems achieve ~50% of this.

            Used Carnot COP to model cooling efficiency — it captures
            the real-world effect where cooling is harder (more expensive)
            on hot days, which the agent must learn to account for.
        """

        # Convert to Kelvin for Carnot formula
        T_cold = crac_setpoint + 273.15   # supply temperature
        T_hot = outside_temp + 10 + 273.15  # condenser temperature

        # Carnot COP = T_cold / (T_hot - T_cold)
        if T_hot <= T_cold:
            return 6.0  # cap at reasonable maximum

        carnot_cop = T_cold / (T_hot - T_cold)

        # Real systems achieve ~50% of Carnot (real-world adjustment)
        real_cop = 0.5 * carnot_cop

        # Clip to realistic range for CRAC units (1.5 to 6.0)
        return float(np.clip(real_cop, 1.5, 6.0))

    def is_in_safe_zone(self, temp: float) -> bool:
        """Returns True if temperature is within ASHRAE safe limits."""
        return self.TEMP_MIN <= temp <= self.TEMP_MAX

    def get_violation_magnitude(self, temp: float) -> float:
        """
        Returns how far outside safe limits the temperature is.
        0.0 means safe. Positive means violation.
        Used for reward penalty calculation in the environment.
        """
        if temp > self.TEMP_MAX:
            return temp - self.TEMP_MAX
        elif temp < self.TEMP_MIN:
            return self.TEMP_MIN - temp
        return 0.0